# .github/workflows/publish.yml in fireschema-ts-client-runtime repo
name: Publish TS Client Runtime

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for provenance generation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or the version specified in package.json engines
          registry-url: 'https://registry.npmjs.org/'

      # Optional: Setup Bun if preferred for install/build/test
      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest

      - name: Install dependencies
        run: npm install # Use 'bun install' if using Bun. Changed from npm ci due to lockfile issues.

      - name: Install Firebase CLI
        run: npm install -g firebase-tools



      - name: Start Firestore Emulator
        run: |
          nohup firebase emulators:start --only firestore --project=demo-project-id &
          sleep 10 # Wait for emulator to start

      - name: Build package
        run: npm run build # Use 'bun run build' if using Bun

      - name: Run tests
        run: npm test # Use 'bun test' if using Bun

      - name: Publish package to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Secret stored in the repository settings
